package middleware

import (
	"context"
	"crypto/rand"
	"encoding/base32"
	"net/http"
	"regexp"

	"github.com/isasumer/go-react-calculator/backend/internal/httpapi"
)

// HeaderRequestID is the header a request ID arrives on and is echoed on.
const HeaderRequestID = "X-Request-ID"

// requestIDPattern is what an incoming ID must look like to be reused. The
// value ends up in every log line for the request and in the problem
// documents the client sees, so it is restricted to characters that cannot
// forge a log line or an HTTP header, and bounded so a client cannot push
// kilobytes into the logs on every request.
var requestIDPattern = regexp.MustCompile(`^[A-Za-z0-9_-]{1,64}$`)

// requestIDEncoding renders the generated bytes as unpadded base32: 26
// characters, safe in a URL, a header and a log line, and itself matching
// requestIDPattern, so an ID this process generated is accepted verbatim by
// the next hop.
var requestIDEncoding = base32.StdEncoding.WithPadding(base32.NoPadding)

// RequestID gives every request an identifier that ties the response the
// client holds to the lines in the server log.
//
// An incoming X-Request-ID is reused when it matches requestIDPattern, so a
// trace started by a proxy or by the frontend survives this hop; anything
// else — absent, oversized, or carrying characters that do not belong in a
// log — is replaced by 16 bytes from crypto/rand. The ID is set on the
// response before the handler runs, so every writer below, down to the panic
// recovery above this middleware, can echo it without knowing it exists, and
// it is put in the request context for [FromContext] and for the problem
// writer.
func RequestID() Middleware {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			id := r.Header.Get(HeaderRequestID)
			if !requestIDPattern.MatchString(id) {
				id = newRequestID()
			}
			w.Header().Set(HeaderRequestID, id)
			next.ServeHTTP(w, r.WithContext(httpapi.ContextWithRequestID(r.Context(), id)))
		})
	}
}

// FromContext returns the ID [RequestID] stored for this request, or "" when
// the handler runs outside the chain — a unit test exercising a handler
// directly, for example.
//
// The value itself lives under an unexported key in package httpapi: that
// package writes the problem documents and has to read the ID, and it cannot
// import this one without a cycle.
func FromContext(ctx context.Context) string { return httpapi.RequestIDFromContext(ctx) }

// requestIDOf returns the ID for this request, from the context if it is
// there and otherwise from the header already set on the response.
//
// The fallback is what lets [Recover] name the ID: it wraps [RequestID]
// rather than the other way round, so it never sees the context RequestID
// derived — but it does share the response writer the ID was set on.
func requestIDOf(w http.ResponseWriter, r *http.Request) string {
	if id := FromContext(r.Context()); id != "" {
		return id
	}
	return w.Header().Get(HeaderRequestID)
}

// newRequestID returns 16 random bytes as 26 base32 characters — 128 bits, so
// collisions are not a thing that happens.
func newRequestID() string {
	var b [16]byte
	// crypto/rand.Read fills b or crashes the program; since Go 1.24 it
	// cannot return an error, and a server without entropy has no business
	// serving anyway.
	_, _ = rand.Read(b[:])
	return requestIDEncoding.EncodeToString(b[:])
}
