#!/bin/sh
# Smoke test for the composed stack: everything a reviewer would click through,
# asserted from outside the containers through the published port only.
#
#   docker compose up --build --wait && scripts/smoke.sh
#   make smoke
#
# Exits non-zero on the first failed assertion, naming what was expected and
# what came back. Requires curl and jq.
#
# Environment:
#   BASE_URL      front door to test            (default http://localhost:8080)
#   BACKEND_PORT  port that must stay private   (default 8081)
#   TIMEOUT       seconds to wait for readiness (default 60)

set -eu

BASE_URL=${BASE_URL:-http://localhost:8080}
BACKEND_PORT=${BACKEND_PORT:-8081}
TIMEOUT=${TIMEOUT:-60}

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT INT TERM

checks=0

pass() {
	checks=$((checks + 1))
	printf 'ok   %s\n' "$1"
}

fail() {
	printf 'FAIL %s\n' "$1" >&2
	shift
	for line in "$@"; do printf '     %s\n' "$line" >&2; done
	exit 1
}

need() {
	command -v "$1" >/dev/null 2>&1 || fail "$1 is required but not installed"
}

need curl
need jq

# body <url> [curl args...] → response body on stdout, status code in $status.
# Keeping them in one call means a single request backs both assertions.
request() {
	url=$1
	shift
	status=$(curl -sS -o "$WORK/body" -D "$WORK/headers" -w '%{http_code}' "$@" "$url")
}

header() {
	# Header names are case-insensitive on the wire; fold before matching.
	tr -d '\r' <"$WORK/headers" | awk -v name="$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')" \
		'BEGIN { FS=": " } tolower($1) == name { $1=""; sub(/^ /, ""); print; exit }'
}

# ---------------------------------------------------------------- readiness --
printf 'waiting for %s/healthz (up to %ss)\n' "$BASE_URL" "$TIMEOUT"
waited=0
until curl -fsS -o /dev/null --max-time 2 "$BASE_URL/healthz" 2>/dev/null; do
	waited=$((waited + 1))
	if [ "$waited" -ge "$TIMEOUT" ]; then
		fail "frontend did not become healthy within ${TIMEOUT}s" \
			"tried GET $BASE_URL/healthz"
	fi
	sleep 1
done
pass "frontend /healthz answered after ${waited}s"

# -------------------------------------------------------- operations listing --
request "$BASE_URL/api/v1/operations"
[ "$status" = 200 ] || fail "GET /api/v1/operations returned $status, want 200" "$(cat "$WORK/body")"
count=$(jq '.operations | length' <"$WORK/body")
[ "$count" = 7 ] || fail "GET /api/v1/operations listed $count operations, want 7" "$(cat "$WORK/body")"
jq -e '.operations | all(has("name") and has("symbol") and has("arity"))' <"$WORK/body" >/dev/null ||
	fail "an operation is missing name/symbol/arity" "$(cat "$WORK/body")"
pass "GET /api/v1/operations lists 7 operations through the proxy"

# ------------------------------------------------------------- happy path --
request "$BASE_URL/api/v1/calculate" \
	-X POST -H 'Content-Type: application/json' \
	-d '{"operation":"add","a":12,"b":7}'
[ "$status" = 200 ] || fail "POST /api/v1/calculate (12+7) returned $status, want 200" "$(cat "$WORK/body")"
result=$(jq -r '.result' <"$WORK/body")
[ "$result" = 19 ] || fail "12 + 7 = $result, want 19" "$(cat "$WORK/body")"
pass "POST /api/v1/calculate 12 + 7 = 19"

# X-Request-ID is generated by nginx when the caller sends none, echoed by the
# backend, and is the id both of them logged.
request_id=$(header x-request-id)
[ -n "$request_id" ] || fail "no X-Request-ID on the response" "$(tr -d '\r' <"$WORK/headers")"
pass "X-Request-ID present on the response ($request_id)"

# ------------------------------------------------------------ problem+json --
request "$BASE_URL/api/v1/calculate" \
	-X POST -H 'Content-Type: application/json' \
	-d '{"operation":"divide","a":1,"b":0}'
[ "$status" = 422 ] || fail "POST 1/0 returned $status, want 422" "$(cat "$WORK/body")"
ctype=$(header content-type)
case $ctype in
application/problem+json*) ;;
*) fail "POST 1/0 content-type is '$ctype', want application/problem+json" ;;
esac
code=$(jq -r '.code' <"$WORK/body")
[ "$code" = DIVISION_BY_ZERO ] || fail "POST 1/0 code is '$code', want DIVISION_BY_ZERO" "$(cat "$WORK/body")"
pass "POST 1/0 → 422 application/problem+json code=DIVISION_BY_ZERO"

# ----------------------------------------------------------- static assets --
request "$BASE_URL/"
[ "$status" = 200 ] || fail "GET / returned $status, want 200"
grep -q '<div id="root">' "$WORK/body" || fail "GET / did not serve the app shell" "$(head -c 400 "$WORK/body")"
case $(header cache-control) in
*no-cache*) ;;
*) fail "GET / cache-control is '$(header cache-control)', want no-cache" ;;
esac
asset=$(tr '"' '\n' <"$WORK/body" | grep -m1 '^/assets/') ||
	fail "GET / referenced no hashed asset under /assets/"
pass "GET / serves index.html (200, no-cache) referencing $asset"

request "$BASE_URL$asset"
[ "$status" = 200 ] || fail "GET $asset returned $status, want 200"
cache=$(header cache-control)
case $cache in
*immutable*) ;;
*) fail "GET $asset cache-control is '$cache', want a public, immutable, max-age=31536000 value" ;;
esac
pass "GET $asset served with Cache-Control: $cache"

# security headers travel with the document, not just the assets
for h in x-content-type-options x-frame-options referrer-policy content-security-policy; do
	[ -n "$(header "$h")" ] || fail "GET $asset is missing the $h header"
done
pass "security headers present (nosniff, DENY, Referrer-Policy, CSP)"

# ------------------------------------------------- backend stays unpublished --
if [ -f compose.override.yaml ] || [ "${SMOKE_ALLOW_BACKEND_PORT:-}" = 1 ]; then
	printf 'skip compose.override.yaml in place: not asserting that :%s is closed\n' "$BACKEND_PORT"
else
	if curl -sS -o /dev/null --max-time 3 "http://localhost:$BACKEND_PORT/healthz" 2>/dev/null; then
		fail "the backend answered on http://localhost:$BACKEND_PORT — it must not be published" \
			"compose.yaml publishes only the frontend; use compose.override.example.yaml to expose it on purpose"
	fi
	pass "backend is not reachable on localhost:$BACKEND_PORT"
fi

printf '\n%s checks passed against %s\n' "$checks" "$BASE_URL"
